apiVersion: apps/v1
kind: Deployment
metadata:
  name: depi-devops-project-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mennabrightskies/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mongodb-url
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: access-token-secret

