version: '3.8'

services:
  frontend:
    container_name: depi-devops-project-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: depi-devops-project-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - ACCESS_TOKEN_SECRET= Rj2S?RVe9[]8-dCS6A**&b5Tsg$gwbg~Bd{*QTK

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
