---
- name: Setup DevOps Tools and Configure SMTP Server
  hosts: all
  become: yes
  vars_prompt:
    - name: smtp_email
      prompt: "Enter your SMTP email (e.g., your_email@gmail.com)"
      private: no

    - name: smtp_password
      prompt: "Enter your SMTP app password"
      private: yes

  tasks:

    - name: Create templates directory
      file:
        path: "~/DEPI-DEVOPS/DEPI-DEVOPS-PROJECT/templates"
        state: directory
        mode: '0755'

    - name: Create Postfix main configuration template
      copy:
        dest: "~/DEPI-DEVOPS/DEPI-DEVOPS-PROJECT/templates/postfix_main.cf.j2"
        content: |
          # Postfix main configuration
          relayhost = [smtp.gmail.com]:587
          smtp_sasl_auth_enable = yes
          smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
          smtp_sasl_security_options = noanonymous
          smtp_tls_security_level = encrypt
          smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt

    - name: Pre-configure Postfix using debconf
      debconf:
        name: postfix
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: "{{ item.vtype }}"
      loop:
        - { question: "postfix/main_mailer_type", value: "Internet Site", vtype: "string" }
        - { question: "postfix/mailname", value: "myserver.local", vtype: "string" }

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - postfix
          - mailutils
        state: present

    - name: Configure Postfix
      template:
        src: postfix_main.cf.j2
        dest: /etc/postfix/main.cf
      notify: Restart Postfix

    - name: Configure SMTP authentication
      copy:
        dest: /etc/postfix/sasl_passwd
        content: |
          [smtp.gmail.com]:587 {{ smtp_email }}:{{ smtp_password }}
        mode: '0600'
      notify:
        - Secure and Compile Authentication File
        - Restart Postfix

    - name: Secure and Compile Authentication File
      command: postmap /etc/postfix/sasl_passwd

    - name: Open SMTP port in UFW
      ufw:
        rule: allow
        port: 587
        proto: tcp

  handlers:
    - name: Restart Postfix
      systemd:
        name: postfix
        state: restarted

    - name: Secure and Compile Authentication File
      command: postmap /etc/postfix/sasl_passwd
